Added calculated variables to long dataframe
brad-cannell/link2care_public pull request #41
Opened 2023-03-28 16:09 UTC by skurada1

#39 #10 

- Added calculated variables using Brad's previous code
- Renamed variables from uppercase to lowercase and provided more intuitive names overall
- 1280 instead of 1184 variables with newly calculated ones added

2023-03-29 16:33 UTC, mbcann01 requested changes
Thank you, @skurada1 ! Will you please just address the changes I commented on and resubmit? I really appreciate your hard work on this!

2023-03-29 16:33 UTC, mbcann01 commented on data_survey_04_tlfb_import.Rmd
> +path <- "~/OneDrive - The University of Texas Health Science Center at Houston/General/link2care_sangeeta_clone/R Data/tlfb.rds"
Please change this to use relative paths.

2023-03-29 16:33 UTC, mbcann01 commented on data_survey_04_tlfb_import.Rmd
> +        x <- suppressWarnings(x_num <- as.numeric(x))
Are we sure we want to suppress this warning? Why are we getting it in the first place?

2023-03-29 16:33 UTC, mbcann01 commented on data_survey_06_bridge_sessions_import.Rmd
> +path <- "~/OneDrive - The University of Texas Health Science Center at Houston/General/link2care_sangeeta_clone/R data/bridge.rds"
Please use relative links.

2023-03-29 16:33 UTC, mbcann01 commented on data_survey_06_bridge_sessions_import.Rmd
> +path <- "~/OneDrive - The University of Texas Health Science Center at Houston/General/link2care_sangeeta_clone/R data/bridge_wide.rds"
Please use relative links.

2023-03-29 16:33 UTC, mbcann01 commented on data_survey_06_bridge_sessions_import.Rmd
It's hard to tell exactly what changed in this file, but I imagine it's good. I'll run it on my computer when the other updates are made.

2023-03-29 16:33 UTC, mbcann01 commented on data_survey_07_ddt_import.Rmd
> +path <- "~/OneDrive - The University of Texas Health Science Center at Houston/General/link2care_sangeeta_clone/R Data/ddt.rds"
Please use relative paths.

2023-03-29 16:33 UTC, mbcann01 commented on data_survey_39_long_calc_import.Rmd
Thanks for all of your hard work on this! I can't wait to try it out. Please just fix the relative path issues that I highlighted and resubmit the pull request. Then, I will run this on my computer. 

Also, let's rename this file, `data_survey_22_calclulated_columns.Rmd` and then change `data_survey_22_codebook.Rmd` to `data_survey_23_codebook.Rmd`.

2023-03-29 16:58 UTC, skurada1 commented on data_survey_04_tlfb_import.Rmd
> +path <- "~/OneDrive - The University of Texas Health Science Center at Houston/General/link2care_sangeeta_clone/R Data/tlfb.rds"
Done. @mbcann01

2023-03-29 17:00 UTC, skurada1 commented on data_survey_06_bridge_sessions_import.Rmd
> +path <- "~/OneDrive - The University of Texas Health Science Center at Houston/General/link2care_sangeeta_clone/R data/bridge_wide.rds"
Done.

2023-03-29 17:01 UTC, skurada1 commented on data_survey_39_long_calc_import.Rmd
Done for both.

2023-03-29 17:02 UTC, skurada1 commented on data_survey_06_bridge_sessions_import.Rmd
Sounds good.

2023-03-29 17:02 UTC, skurada1 commented on data_survey_06_bridge_sessions_import.Rmd
> +path <- "~/OneDrive - The University of Texas Health Science Center at Houston/General/link2care_sangeeta_clone/R data/bridge.rds"
Done.

2023-03-29 17:03 UTC, skurada1 commented on data_survey_04_tlfb_import.Rmd
> +        x <- suppressWarnings(x_num <- as.numeric(x))
I believe it's because of the coercing of empty values to "NA," which makes it think it's a character rather than numeric. So, I added the suppress warnings because it seemed to run and import properly with that incorporated. @mbcann01

2023-03-29 17:06 UTC, skurada1 commented
#39 #10 

Redid relative paths and renamed syntax/codebook files @mbcann01

2023-04-11 19:47 UTC, skurada1 commented
@mbcann01 

Coded source attributes for vars. 1-1077, until var. 1078 titled "sq_7b2"
Unsure how to code for REDCap, so haven't finished 202 variables yet.

2023-04-13 18:52 UTC, closed without merging